"""empty message

Revision ID: 373489b9063f
Revises: 4c1e3b7c1e92
Create Date: 2023-05-04 08:54:55.536407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '373489b9063f'
down_revision = '4c1e3b7c1e92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_purchase', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('purchase_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('product_purchase_id_key', type_='unique')
        batch_op.drop_constraint('product_purchase_product_id_key', type_='unique')
        batch_op.drop_constraint('product_purchase_purchase_id_key', type_='unique')
        batch_op.drop_constraint('product_purchase_quantity_key', type_='unique')

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_constraint('purchase_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.create_unique_constraint('purchase_id_key', ['id'])
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('product_purchase', schema=None) as batch_op:
        batch_op.create_unique_constraint('product_purchase_quantity_key', ['quantity'])
        batch_op.create_unique_constraint('product_purchase_purchase_id_key', ['purchase_id'])
        batch_op.create_unique_constraint('product_purchase_product_id_key', ['product_id'])
        batch_op.create_unique_constraint('product_purchase_id_key', ['id'])
        batch_op.alter_column('purchase_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
