"""empty message

Revision ID: 5b39ee179bcb
Revises: 373489b9063f
Create Date: 2023-05-21 11:24:39.001621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b39ee179bcb'
down_revision = '373489b9063f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.drop_constraint('product_description_key', type_='unique')
        batch_op.drop_constraint('product_ingredients_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_unique_constraint('product_ingredients_key', ['ingredients'])
        batch_op.create_unique_constraint('product_description_key', ['description'])
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
