"""empty message

Revision ID: c042a370ee2a
Revises: 32f958cc28a4
Create Date: 2023-05-02 06:48:05.767423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c042a370ee2a'
down_revision = '32f958cc28a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bestseller', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('bestseller_id_key', type_='unique')
        batch_op.drop_constraint('bestseller_position_key', type_='unique')
        batch_op.drop_constraint('bestseller_product_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bestseller', schema=None) as batch_op:
        batch_op.create_foreign_key('bestseller_product_id_fkey', 'product', ['product_id'], ['id'])
        batch_op.create_unique_constraint('bestseller_position_key', ['position'])
        batch_op.create_unique_constraint('bestseller_id_key', ['id'])
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
